//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNhanSu.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ChuyenCan
    {
        [Display(Name = "Mã chuyên cần")]
        public int MACC { get; set; }
        [Display(Name = "Mã nhân viên")]
        public string MANV { get; set; }
        [Display(Name = "Lý do")]
        public string LYDO { get; set; }
        [DisplayFormat(DataFormatString = "{0:d}")]
        [Display(Name = "Ngày vắng")]
        public System.DateTime NGAYVANG { get; set; }
    
        public virtual NhanVien NhanVien { get; set; }
    }
}
