//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNhanSu.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Luong
    {
        [Display(Name = "Mã nhân viên")]
        public string MANV { get; set; }
        [Display(Name = "Lương cơ bản")]
        [Required(ErrorMessage = "Phải nhập lương cơ bản")]
        public Nullable<float> LUONGCOBAN { get; set; }
        [Display(Name = "Hệ số lương")]
        [Required(ErrorMessage = "Phải nhập hệ số lương")]
        public Nullable<float> HESOLUONG { get; set; }
        [Display(Name = "Phụ cấp")]
        [Required(ErrorMessage = "Phải nhập phụ cấp")]
        public Nullable<float> PHUCAP { get; set; }
    
        public virtual NhanVien NhanVien { get; set; }
    }
}
