//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNhanSu.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class NhanVien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NhanVien()
        {
            this.ChuyenPhongBans = new HashSet<ChuyenPhongBan>();
            this.ChuyenCans = new HashSet<ChuyenCan>();
            this.QuanLyLuongs = new HashSet<QuanLyLuong>();
        }

        [Required(ErrorMessage = "Phải nhập mã nhân viên")]
        [Display(Name = "Mã nhân viên")]
        public string MANV { get; set; }
        [Display(Name = "Họ tên")]
        [Required(ErrorMessage = "Phải nhập họ tên")]
        public string HOTEN { get; set; }
        [Display(Name = "Ảnh đại diện")]
        public string ANHDAIDIEN { get; set; }
        [Display(Name = "Dân tộc")]
        public string DANTOC { get; set; }
        [Display(Name = "Giới tính")]
        public string GIOITINH { get; set; }
        [Display(Name = "Số điện thoại")]
        [Phone(ErrorMessage = "Phải nhập đúng định dạng số điện thoại")]
        public string SODIENTHOAI { get; set; }
        [Display(Name = "Quê quán")]
        public string QUEQUAN { get; set; }
        [DisplayFormat(DataFormatString = "{0:d}")]
        [Display(Name = "Ngày sinh")]
        public Nullable<System.DateTime> NGAYSINH { get; set; }
        public string MACV { get; set; }
        public string MATDHV { get; set; }
        public string MAPB { get; set; }
        [Display(Name = "Ngày bắt đầu")]
        [DisplayFormat(DataFormatString = "{0:d}")]
        public Nullable<System.DateTime> NGAYBATDAU { get; set; }
        [Display(Name = "Chuyên ngành")]
        public string CHUYENNGANH { get; set; }

        [Display(Name = "Chức vụ")]
        public virtual ChucVu ChucVu { get; set; }
        [Display(Name = "Phòng ban")]
        public virtual PhongBan PhongBan { get; set; }
        [Display(Name = "Trình độ học vấn")]
        public virtual TrinhDoHocVan TrinhDoHocVan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChuyenPhongBan> ChuyenPhongBans { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChuyenCan> ChuyenCans { get; set; }
        public virtual Luong Luong { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QuanLyLuong> QuanLyLuongs { get; set; }
    }
}
