//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNhanSu.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class PhongBan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PhongBan()
        {
            this.NhanViens = new HashSet<NhanVien>();
            this.ChuyenPhongBans = new HashSet<ChuyenPhongBan>();
            this.ChuyenPhongBans1 = new HashSet<ChuyenPhongBan>();
        }

        [Required(ErrorMessage = "Phải nhập mã phòng ban")]
        [Display(Name = "Mã phòng ban")]
        public string MAPB { get; set; }
        [Required(ErrorMessage = "Phải nhập tên phòng ban")]
        [Display(Name = "Tên phòng ban")]
        public string TENPB { get; set; }
        [Display(Name = "Địa chỉ")]
        public string DIACHI { get; set; }
        [Display(Name = "Số diện thoại")]
        public string SODIENTHOAI { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NhanVien> NhanViens { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChuyenPhongBan> ChuyenPhongBans { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChuyenPhongBan> ChuyenPhongBans1 { get; set; }
    }
}
